"""Search for a conductor-3 harmonic formula for Zagier's C companion.

The integral row has the symmetric constant-term representation

    A_n = sum_{a+b+c=n} multinomial(n;a,b,c)^2.

We fit its canonical second solution against the weight-two, character-odd
alphabet generated by K_{-3}^{(2)}(3x) and H_y K_{-3}^{(1)}(3x).
All discovery linear algebra is over a large prime; reported formulas are
reconstructed and checked independently over Q on held-out values.
"""

from fractions import Fraction as Q
from math import factorial
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "work" / "sporadic"))
sys.path.insert(0, str(ROOT / "work" / "lbw"))

from core import PRIMES, consistency, crt, ratrecon  # noqa: E402
from sporadic import gen_B  # noqa: E402


P = PRIMES[0]


def companion(N):
    # R2 parameters (a,b,c)=(10,3,9) in the convention of sporadic.py.
    return gen_B(2, (10, 3, 9), N)


def cells_mod(n, q, fac, ifac):
    out = []
    nf = fac[n]
    for a in range(n + 1):
        for b in range(n - a + 1):
            c = n - a - b
            m = nf * ifac[a] % q * ifac[b] % q * ifac[c] % q
            out.append((a, b, c, m * m % q))
    return out


def tables_mod(M, q):
    H = np.zeros(3 * M + 1, dtype=np.int64)
    K1 = np.zeros(3 * M + 1, dtype=np.int64)
    K2 = np.zeros(3 * M + 1, dtype=np.int64)
    for m in range(1, 3 * M + 1):
        inv = pow(m, q - 2, q)
        ch = 0 if m % 3 == 0 else (1 if m % 3 == 1 else -1)
        H[m] = (H[m - 1] + inv) % q
        K1[m] = (K1[m - 1] + ch * inv) % q
        K2[m] = (K2[m - 1] + ch * inv * inv) % q
    return H, K1, K2


def arg_values(n, a, b, c):
    return {
        "n": n,
        "a": a,
        "b": b,
        "c": c,
        "n-a": n - a,
        "n-b": n - b,
        "n-c": n - c,
    }


BASE_ARGS = ("n", "a", "b", "c", "n-a", "n-b", "n-c")
H_ARGS = tuple((scale, x) for scale in (1, 3) for x in BASE_ARGS)
K_ARGS = BASE_ARGS


def features():
    fs = [("K2", x) for x in K_ARGS]
    fs += [("HK", hs, hx, kx) for hs, hx in H_ARGS for kx in K_ARGS]
    return fs


FEATURES = features()


def fname(f):
    if f[0] == "K2":
        return f"K2(3*{f[1]})"
    return f"H({f[1]}*{f[2]})*K1(3*{f[3]})"


def design(N, q, fs=FEATURES):
    fac = [1] * (N + 1)
    for j in range(1, N + 1):
        fac[j] = fac[j - 1] * j % q
    ifac = [pow(x, q - 2, q) for x in fac]
    H, K1, K2 = tables_mod(N, q)
    A = np.zeros((N, len(fs)), dtype=np.int64)
    for n in range(1, N + 1):
        for a, b, c, shell in cells_mod(n, q, fac, ifac):
            av = arg_values(n, a, b, c)
            for j, f in enumerate(fs):
                if f[0] == "K2":
                    v = K2[3 * av[f[1]]]
                else:
                    v = H[f[1] * av[f[2]]] * K1[3 * av[f[3]]] % q
                A[n - 1, j] = (A[n - 1, j] + shell * v) % q
    return A


def rhs(N, q):
    B = companion(N + 2)
    out = []
    for n in range(1, N + 1):
        x = B[n]
        out.append((x.numerator % q) * pow(x.denominator % q, q - 2, q) % q)
    return np.array(out, dtype=np.int64)


def discover(N=125):
    A = design(N, P)
    b = rhs(N, P)
    r = consistency(A, b, P)
    print(f"rows={N} cols={len(FEATURES)} rank={r['rank']} consistent={r['consistent']}")
    if not r["consistent"]:
        return None
    support = r["pivots"]
    print(f"initial support={len(support)}")
    return support


def solve_support(support, N=125, nprimes=4):
    fs = [FEATURES[j] for j in support]
    sols = []
    mods = PRIMES[:nprimes]
    for q in mods:
        A = design(N, q, fs)
        r = consistency(A, rhs(N, q), q)
        if not r["consistent"] or r["rank"] != len(fs):
            raise RuntimeError(f"bad support modulo {q}: rank={r['rank']}")
        sols.append([int(x) for x in r["sol"]])
    coeffs = []
    for j in range(len(fs)):
        a, M = crt([s[j] for s in sols], mods)
        x = ratrecon(a, M)
        if x is None:
            raise RuntimeError(f"rational reconstruction failed at {j}")
        coeffs.append(x)
    terms = [(x, f) for x, f in zip(coeffs, fs) if x]
    for x, f in terms:
        print(f"{x!s:>16}  {fname(f)}")
    return terms


def exact_tables(M):
    H = [Q(0)] * (3 * M + 1)
    K1 = [Q(0)] * (3 * M + 1)
    K2 = [Q(0)] * (3 * M + 1)
    for m in range(1, 3 * M + 1):
        ch = 0 if m % 3 == 0 else (1 if m % 3 == 1 else -1)
        H[m] = H[m - 1] + Q(1, m)
        K1[m] = K1[m - 1] + Q(ch, m)
        K2[m] = K2[m - 1] + Q(ch, m * m)
    return H, K1, K2


def check_exact(terms, ns):
    H, K1, K2 = exact_tables(max(ns))
    B = companion(max(ns) + 2)
    for n in ns:
        z = Q(0)
        nf = factorial(n)
        for a in range(n + 1):
            for b in range(n - a + 1):
                c = n - a - b
                av = arg_values(n, a, b, c)
                shell = (nf // (factorial(a) * factorial(b) * factorial(c))) ** 2
                w = Q(0)
                for co, f in terms:
                    if f[0] == "K2":
                        v = K2[3 * av[f[1]]]
                    else:
                        v = H[f[1] * av[f[2]]] * K1[3 * av[f[3]]]
                    w += co * v
                z += shell * w
        ok = z == B[n]
        print(f"exact n={n}: {ok}")
        if not ok:
            print(" got", z, "expected", B[n], "difference", z - B[n])
            return False
    return True


if __name__ == "__main__":
    support = discover()
    if support is not None:
        terms = solve_support(support)
        check_exact(terms, range(126, 136))
