display2d:false$
load("zeilberger")$
S:binomial(n,k)^2*binomial(n+k,k)*binomial(2*k,n)$
rn:shiftQuo(S,n)$
rm:ratsimp(1/subst(n=n-1,rn))$
shell:ratsimp((n+1)^3*rn-(2*n+1)*(13*n^2+13*n+4)-n*(27*n^2-3)*rm)$
print("GOSPER SHELL =",Gosper(S*shell,k))$
print("PARGOSPER =",parGosper(S,k,n,2))$
shellf:ratsimp(-3*(n+1)*(3*n+2)*(3*n+4)
 -(2*n+3)*(13*n^2+39*n+30)*rn
 +(n+2)^3*rn*subst(n=n+1,rn))$
print("GOSPER FORWARD SHELL =",Gosper(S*shellf,k))$
print("GOSPER SIMPLIFIED =",Gosper(minfactorial(makefact(S*shellf)),k))$
Sf:(n+k)!*(2*k)!/(k!^3*(n-k)!^2*(2*k-n)!)$
print("GOSPER FACTORIAL SHELL =",Gosper(Sf*shellf,k))$
print("PARGOSPER ORDER0 =",parGosper(S*shellf,k,n,0))$
zc:k^2*(n-2*k)*(n-2*k+1)
 *(7*n^3-26*k*n^2+39*n^2+15*k^2*n-91*k*n+72*n
   +22*k^2-78*k+44)/((n-k+1)^2*(n-k+2)^2)$
print("CERT CHECK =",ratsimp(subst(k=k+1,zc)*shiftQuo(S,k)-zc-shellf))$
quit();
