import sympy as sp

n, h, k, m = sp.symbols('n h k m', integer=True)

# We derive TREC by direct manipulation, working with symbolic small n via generating
# series truncation, to find the correct auxiliary "Way A / Way B" identity mirroring
# CatalanEndpoint.lean's catalanM_wayA / catalanM_wayB approach.
#
# Strategy: verify TREC numerically to high n for many h (already done in
# verify_zagier_B_endpoint.py). Here we instead derive, via the *finite* recurrence for
# C directly (no generating functions), an auxiliary two-term "reduction" showing how
# n^2 S_n + h^3 (n-2)(n-1) S_{n-3} simplifies using only:
#   * Pascal's rule on binomial coefficients: C(n,k) = C(n-1,k) + C(n-1,k-1)
#   * the defining recurrence for C_k when 1 <= k
#
# We build S_n = sum_k C(n,k) (-h)^{n-k} C_k symbolically for concrete small n (as
# polynomials in h and the abstract values C_0..C_n), then substitute the recurrence
# C_{k+1} = (h(3k^2+3k+1) C_k - 3h^2k^2 C_{k-1})/(k+1)^2 for k>=1, to see the exact
# elimination combination needed and confirm which linear combination of shifted
# recurrence instances reproduces TREC. We just confirm TREC symbolically via C(x)
# formal power series in x with C_k as unspecified symbols up to a cutoff, which is the
# same conjugation argument from the paper but checked by direct polynomial algebra
# (no analytic operator manipulations) for a robust "elimination certificate".

N = 12  # unroll length
Cs = sp.symbols('C0:%d' % (N + 2))

def Cval(k):
    return Cs[k]

# S_n via direct binomial transform definition
def S(nn):
    return sum(sp.binomial(nn, k) * (-h) ** (nn - k) * Cval(k) for k in range(nn + 1))

# recurrence relation for C, used only to eliminate/verify (not needed for S's def)
def rec_lhs(k):
    # (k+1)^2 C_{k+1} - h(3k^2+3k+1) C_k + 3h^2k^2 C_{k-1} = 0   for k>=1
    return (k + 1) ** 2 * Cval(k + 1) - h * (3 * k ** 2 + 3 * k + 1) * Cval(k) + 3 * h ** 2 * k ** 2 * Cval(k - 1)

# Build TREC LHS - RHS as a polynomial in Cs, h for a given n, then reduce it modulo
# the ideal generated by rec_lhs(1),...,rec_lhs(n-1) (the only relations available),
# to see if it is a combination of these with h-polynomial coefficients (an explicit
# elimination certificate), matching the "linear_combination" style needed in Lean.

def trec_defect(nn):
    lhs = nn ** 2 * S(nn) + h ** 3 * (nn - 2) * (nn - 1) * S(nn - 3) if nn >= 3 else None
    return lhs

for nn in range(3, 8):
    expr = sp.expand(trec_defect(nn) - (-h) ** (nn - 1))
    # try to express expr as sum_{k=1}^{nn-1} coeff_k(h) * rec_lhs(k)
    rels = [rec_lhs(k) for k in range(1, nn)]
    unknown_coeffs = sp.symbols('a1:%d' % nn)
    combo = sum(unknown_coeffs[k - 1] * rels[k - 1] for k in range(1, nn))
    diff = sp.expand(expr - combo)
    # diff should be solvable to 0 for some choice of unknown_coeffs (polynomials in h);
    # collect diff as polynomial in Cs and match coefficients.
    polydiff = sp.Poly(diff, *Cs)
    coeffs_by_monom = polydiff.terms()
    # Solve linear system for unknown_coeffs (which may depend on h) by matching each
    # C-monomial's coefficient (a polynomial in h and unknown_coeffs) to zero.
    eqs = []
    for monom, c in coeffs_by_monom:
        eqs.append(sp.expand(c))
    sol = sp.solve(eqs, list(unknown_coeffs), dict=True)
    print(nn, 'solutions:', sol)
