#!/usr/bin/env python3
"""Symbolically certify the four scalar recurrences used in the Catalan proof.

The verification takes place in the difference field generated by

    c_n = binomial(2*n,n),
    A_n = 3*H_n/4-H_(2*n)/2,
    D_n = K_(2*n)^(1),
    Q_n = K_(2*n)^(2),
    eps_n = (-1)^n.

Only the displayed first-order shift laws are used, so a zero returned here is
an identity of rational functions, not a finite-data check.
"""

import sympy as sp


n = sp.symbols("n", integer=True, nonnegative=True)
A, D, Q, eps = sp.symbols("A D Q eps")


def shifted_data(max_shift):
    """Return c_(n+i)/c_n, A_(n+i), D_(n+i), Q_(n+i), eps_(n+i)."""
    out = []
    cfac = sp.Integer(1)
    aa, dd, qq, ee = A, D, Q, eps
    for i in range(max_shift + 1):
        out.append((sp.factor(cfac), aa, dd, qq, ee))
        k = n + i
        cfac *= 2 * (2*k + 1) / (k + 1)
        aa += k / (2 * (k + 1) * (2*k + 1))
        dd += ee / (2*k + 1)
        qq += ee / (2*k + 1)**2
        ee = -ee
    return out


def certify(name, coefficients, values):
    expression = sp.together(sum(p*v for p, v in zip(coefficients, values)))
    numerator = sp.cancel(expression).as_numer_denom()[0]
    poly = sp.Poly(sp.expand(numerator), A, D, Q, eps)
    assert poly.is_zero, f"{name} failed: {sp.factor(numerator)}"
    print(f"{name}: certified identically")


def main():
    shifts = shifted_data(4)
    cvals = [s[0] for s in shifts]
    avals = [s[0]*s[1] for s in shifts]
    dvals = [s[0]*s[2] for s in shifts]
    evals = [s[0]*(s[3]/2 + s[1]*s[2]) for s in shifts]

    rc = [-2*(2*n + 1), n + 1]
    ra = [
        4*(n + 1)*(2*n + 1)**2,
        -2*(4*n**3 + 12*n**2 + 10*n + 1),
        n*(n + 2)**2,
    ]
    rd = [
        -4*(2*n + 1)**2,
        -4*(n + 1),
        (n + 1)*(n + 2),
    ]
    re = [
        16*(2*n + 1)**3*(2*n + 3)
        *(8*n**5 + 84*n**4 + 336*n**3 + 628*n**2 + 522*n + 129),
        32*(2*n + 3)
        *(16*n**7 + 184*n**6 + 832*n**5 + 1824*n**4
          + 1782*n**3 + 48*n**2 - 1215*n - 660),
        -8*(32*n**9 + 528*n**8 + 3704*n**7 + 14356*n**6
            + 33332*n**5 + 46676*n**4 + 36898*n**3
            + 12653*n**2 - 1179*n - 1431),
        -8*(n + 3)**2
        *(8*n**6 + 72*n**5 + 228*n**4 + 270*n**3
          - 44*n**2 - 347*n - 211),
        (n + 3)**2*(n + 4)**2
        *(8*n**5 + 44*n**4 + 80*n**3 + 44*n**2 - 22*n - 25),
    ]

    certify("R_c c", rc, cvals)
    certify("R_a a", ra, avals)
    certify("R_d d", rd, dvals)
    certify("R_e e", re, evals)
    print("all scalar recurrence certificates are exact")


if __name__ == "__main__":
    main()
