"""
Creative-telescoping certificate for the Catalan harmonic companion
(Observation obs:Catalan / Conjecture conj:Catalan in papers_out/harmonic_jets).

Target: with
    S(n,k) = C(n,k) C(2k,k) C(2n-2k,n-k),
    w(n,k) = 1/2 K2_{2k} + (3/4 H_k - 1/2 H_{2k}) (K1_{2k} - K1_{2n-2k}),
    B(n)   = sum_k S(n,k) w(n,k),
prove   (n+1)^2 B(n+1) = (12n^2+12n+4) B(n) - 32 n^2 B(n-1)   for all n >= 1.

Method (mirrors work/z2cf/lean_certificate.py): write the cell
    C(n,k) = (n+1)^2 S(n+1,k) w(n+1,k) - (12n^2+12n+4) S(n,k) w(n,k)
             + 32 n^2 S(n-1,k) w(n-1,k)
in the letter algebra generated by
    s = (-1)^k,  Hk = H_k,  H2 = H_{2k},  K1a = K1_{2k}, K1b = K1_{2n-2k},
    K2a = K2_{2k},
with e = (-1)^n treated as a +-1 parameter (parity split in n), and solve for
    Psi(n,k) = S(n,k) * sum_m c_m(n,k) M_m
with rational c_m such that Psi(n,k+1) - Psi(n,k) = C(n,k), grading by letter
monomial and solving the resulting first-order rational recurrences top-down
in weight.  Every solve is exact (sympy over Q(n,e)); the result is verified
independently in exact rational arithmetic at the end.
"""
import sympy as sp
from itertools import product

n, k, e = sp.symbols('n k e')  # e = (-1)^n, e**2 = 1

# ---------------------------------------------------------------- letter algebra
# monomial = (s, hk, h2, k1a, k1b, k2a); s in {0,1}; weight = hk+h2+k1a+k1b+2*k2a
LETTERS = ['s', 'Hk', 'H2', 'K1a', 'K1b', 'K2a']
WEIGHT = dict(s=0, Hk=1, H2=1, K1a=1, K1b=1, K2a=2)

def weight(m):
    return m[1] + m[2] + m[3] + m[4] + 2 * m[5]

# increments under k -> k+1:  letter' = letter + inc  (inc may contain the sign
# letter s and the parameter e).  We represent inc as an element {monomial: coeff}.
ONE = (0, 0, 0, 0, 0, 0)
S1 = (1, 0, 0, 0, 0, 0)

INC = {
    'Hk':  {ONE: 1 / (k + 1)},
    'H2':  {ONE: 1 / (2*k + 1) + 1 / (2*k + 2)},
    'K1a': {S1: 1 / (2*k + 1)},
    'K2a': {S1: 1 / (2*k + 1)**2},
    'K1b': {S1: e / (2*n - 2*k - 1)},
}

def emul(a, b):
    """product of two elements (dict monomial -> coeff), reducing s^2 -> 1."""
    out = {}
    for ma, ca in a.items():
        for mb, cb in b.items():
            m = ((ma[0] + mb[0]) % 2,) + tuple(ma[i] + mb[i] for i in range(1, 6))
            out[m] = out.get(m, 0) + ca * cb
    return {m: sp.cancel(c) for m, c in out.items() if sp.cancel(c) != 0}

def eadd(a, b):
    out = dict(a)
    for m, c in b.items():
        out[m] = out.get(m, 0) + c
    return {m: sp.cancel(c) for m, c in out.items() if sp.cancel(c) != 0}

def escale(a, f):
    return {m: sp.cancel(c * f) for m, c in a.items() if sp.cancel(c * f) != 0}

def shift_monomial(m):
    """expand M_m(k+1) in terms of base monomials at k (coeffs rational in n,k,e).
    Also flips s: s(k+1) = -s(k)."""
    out = {ONE: sp.Integer(1)}
    for i, L in enumerate(LETTERS[1:], start=1):
        base = {tuple(1 if j == i else 0 for j in range(6)): sp.Integer(1)}
        term = eadd(base, INC[L])
        for _ in range(m[i]):
            out = emul(out, term)
    if m[0]:
        # sigma(k+1) = -sigma(k); increments above are already at base k
        out = emul(out, {S1: sp.Integer(-1)})
    return out

def shift_element(el, subs_k1=True):
    out = {}
    for m, c in el.items():
        cs = sp.cancel(c.subs(k, k + 1)) if subs_k1 else c
        for mm, cc in shift_monomial(m).items():
            out[mm] = out.get(mm, 0) + cs * cc
    return {m: sp.cancel(c) for m, c in out.items() if sp.cancel(c) != 0}

# ---------------------------------------------------------------- the cell
# w in letters
W = {(0, 0, 0, 0, 0, 1): sp.Rational(1, 2),
     (0, 1, 0, 1, 0, 0): sp.Rational(3, 4),
     (0, 1, 0, 0, 1, 0): sp.Rational(-3, 4),
     (0, 0, 1, 1, 0, 0): sp.Rational(-1, 2),
     (0, 0, 1, 0, 1, 0): sp.Rational(1, 2)}

def w_shift_n(j):
    """w(n+j,k) expressed in base letters at (n,k); j in {-1,0,1}.
    Only K1b moves: K1b(n+1) = K1b + e*s/(2n-2k+1);
                    K1b(n-1) = K1b + e*s/(2n-2k-1)  [note: +, since e=( -1)^n]."""
    if j == 0:
        return W
    delta = e / (2*n - 2*k + 1) if j == 1 else e / (2*n - 2*k - 1)
    out = {}
    for m, c in W.items():
        if m[4] == 0:
            out[m] = out.get(m, 0) + c
        else:
            out[m] = out.get(m, 0) + c
            m0 = (1 - m[0] if False else (m[0] + 1) % 2,) + m[1:4] + (0,) + (m[5],)
            out[m0] = out.get(m0, 0) + c * delta
    return {m: sp.cancel(c) for m, c in out.items() if sp.cancel(c) != 0}

# shell ratios
rho_p = 2*(n + 1)*(2*n - 2*k + 1) / (n + 1 - k)**2          # S(n+1,k)/S(n,k)
rho_m = (n - k)**2 / (2*n*(2*n - 2*k - 1))                  # S(n-1,k)/S(n,k)
r     = (n - k)**2*(2*k + 1) / ((k + 1)**2*(2*n - 2*k - 1)) # S(n,k+1)/S(n,k)

Lp, L0, Lm = (n + 1)**2, -(12*n**2 + 12*n + 4), 32*n**2

CELL = eadd(eadd(escale(w_shift_n(1), Lp * rho_p), escale(W, L0)),
            escale(w_shift_n(-1), Lm * rho_m))

print('cell monomials (by weight):')
for m in sorted(CELL, key=weight, reverse=True):
    print('  w=%d %s : %s' % (weight(m), m, sp.factor(CELL[m])))

# ---------------------------------------------------------------- rational solver
K = k

def linfactors(poly):
    """factor a polynomial in k over Q(n,e); return list of (factor, mult)."""
    p = sp.Poly(sp.expand(poly), K)
    if p.degree() <= 0:
        return []
    c, fl = sp.factor_list(sp.expand(poly), K)
    return [(f, m) for f, m in fl if sp.Poly(f, K).degree() >= 1]

def univ_denominator(A, B, J=12):
    """Abramov universal denominator for A(k) phi(k+1) + B(k) phi(k) = C(k):
    poles of phi divide u with A1(k)=A(k-1), B1(k)=B(k)."""
    A1 = sp.expand(A.subs(K, K - 1))
    B1 = sp.expand(B)
    u = sp.Integer(1)
    for j in range(J, -1, -1):
        g = sp.gcd(sp.Poly(A1, K, domain=f'QQ(n,e)'),
                   sp.Poly(B1.subs(K, K + j), K, domain=f'QQ(n,e)'))
        g = g.as_expr()
        if sp.Poly(g, K).degree() >= 1:
            A1 = sp.cancel(A1 / g)
            B1 = sp.cancel(B1 / g.subs(K, K - j))
            for i in range(j + 1):
                u *= g.subs(K, K - i)
    return sp.expand(u)

def solve_first_order(diag, g, maxdeg_extra=6):
    """solve  diag * r(k) * phi(k+1) - phi(k) = g(k)  for rational phi, or None.
    diag is +1 or -1 (sign-letter diagonal)."""
    g = sp.cancel(sp.together(g))
    if g == 0:
        return sp.Integer(0)
    rr = sp.cancel(diag * r)
    An, Ad = sp.fraction(sp.cancel(rr))
    Gn, Gd = sp.fraction(g)
    # A(k) phi(k+1) + B(k) phi(k) = C(k)
    A = sp.expand(An * Gd)
    B = sp.expand(-Ad * Gd)
    C = sp.expand(Gn * Ad)
    u = univ_denominator(A, B)
    # phi = z(k)/u(k), z polynomial:  A z(k+1)/u(k+1) + B z(k)/u(k) = C
    u1 = u.subs(K, K + 1)
    Aa = sp.cancel(A * u / sp.gcd(sp.Poly(u1, K, domain='QQ(n,e)'),
                                  sp.Poly(u1, K, domain='QQ(n,e)')).as_expr())
    # clear denominators: A z(k+1) u(k) + B z(k) u(k+1) = C u(k) u(k+1)
    lhsA = sp.expand(A * u)
    lhsB = sp.expand(B * u1)
    rhs = sp.expand(C * u * u1)
    # common content
    gg = sp.gcd(sp.gcd(sp.Poly(lhsA, K, domain='QQ(n,e)'),
                       sp.Poly(lhsB, K, domain='QQ(n,e)')),
                sp.Poly(rhs, K, domain='QQ(n,e)')).as_expr()
    lhsA, lhsB, rhs = [sp.cancel(x / gg) for x in (lhsA, lhsB, rhs)]
    dA = sp.Poly(lhsA, K).degree(); dB = sp.Poly(lhsB, K).degree()
    dR = sp.Poly(rhs, K).degree()
    dz = max(dR - max(dA, dB), 0) + maxdeg_extra
    coeffs = sp.symbols('z0:%d' % (dz + 1))
    z = sum(c * K**i for i, c in enumerate(coeffs))
    eq = sp.expand(lhsA * z.subs(K, K + 1) + lhsB * z - rhs)
    eqs = [sp.Eq(sp.cancel(c), 0) for c in sp.Poly(eq, K).all_coeffs()]
    sol = sp.solve(eqs, coeffs, dict=True)
    if not sol:
        return None
    zz = z.subs(sol[0]).subs({c: 0 for c in coeffs})
    return sp.cancel(zz / u)

# ---------------------------------------------------------------- graded solve
def delta_of(cm, m):
    """element  r * shift(c_m M_m) - c_m M_m   (i.e. Delta_k(S c_m M_m)/S)."""
    shifted = shift_element({m: cm})
    return eadd(escale(shifted, r), {m: -cm})

residual = dict(CELL)
cert = {}
order = sorted(residual, key=weight, reverse=True)
seen = set()
while residual:
    m = max(residual, key=weight)
    g = residual.pop(m)
    diag = -1 if m[0] else 1
    phi = solve_first_order(diag, g)
    if phi is None:
        print('OBSTRUCTION at monomial', m, ': no rational solution')
        print('  rhs =', sp.factor(g))
        break
    cert[m] = phi
    contrib = delta_of(phi, m)
    contrib.pop(m, None)  # the diagonal reproduces g by construction
    for mm, cc in contrib.items():
        residual[mm] = sp.cancel(residual.get(mm, 0) - cc)
        if residual[mm] == 0:
            residual.pop(mm)
else:
    print('\nCOMPLETE CERTIFICATE (Psi = S * sum c_m M_m):')
    for m in sorted(cert, key=weight, reverse=True):
        print('  %s : %s' % (m, sp.factor(cert[m])))
