"""Emit the four cell-certificate components in `y`-graded form: the bivariate identity
is stated as a polynomial in y whose every coefficient is a sum of univariate polynomials
in x that cancels.  Each coefficient is closed by a cheap univariate `ring`."""
import sympy as sp
import pickle
import functools
import sys

import os
SP = os.path.dirname(os.path.abspath(__file__)) + '/'
exec(open(SP + 'emit_all.py').read().split("out = ['''")[0])

HEAD = '''/-
# Cell-certificate component `%s` for the minimal ζ(2) companion

Machine-generated by `work/z2cf/lean_certificate.py` / `emit_graded.py`; see
`work/Z2_MINIMAL_LEAN.md`.

This is the **minimally-cleared, `y`-graded** form of one letter-monomial component of the
cell identity `star_z2`, in two free rationals `x` (the base index `n`) and `y` (the
summation index `k`).  Writing `r(y) = (x−y)²(x+y+1)/(y+1)³ = S(x,y+1)/S(x,y)` and
`X, C, B, A` for the certificate cofactors `χ, γ, β, α`, this file encodes

    %s

Two formulation choices are load-bearing and must not be "simplified":

* **minimal clearing** — the rational form with `field_simp` does not elaborate;
* **`y`-grading** — the ungraded bivariate identity is one enormous `ring` call
  (53 min for `β`, and worse for `α`).  Grading in `y` turns it into one cheap
  univariate `ring` per coefficient.

Cleared by the common factor `%s`.
-/
import Mathlib

namespace ZetaLucas
'''


def emit(tag):
    polys, g = clear(COMPS[tag])
    dy = max(sp.Poly(q, y).degree() for q in polys)
    groups = []
    for j in range(dy + 1):
        cs = [sp.expand(sp.Poly(q, y).coeff_monomial(y**j)) for q in polys]
        cs = [c for c in cs if c != 0]
        assert sp.expand(sum(cs)) == 0, (tag, j)
        groups.append(cs)
    body = HEAD % (tag, DOC[tag], str(sp.factor(g)).replace('**', '^'))
    lhs = []
    haves = []
    for j, cs in enumerate(groups):
        e = ' + '.join('(%s)' % str(c).replace('**', '^') for c in cs)
        haves.append('  have h%d : %s = 0 := by ring' % (j, e))
        lhs.append('(%s)' % e if j == 0 else '(%s) * y^%d' % (e, j))
    body += ('\nset_option maxRecDepth 1000000 in\n'
             'theorem z2cert_%s (x y : ℚ) :\n    %s = 0 := by\n%s\n'
             '  simp only [%s]\n  ring\n\nend ZetaLucas\n'
             % (tag, '\n      + '.join(lhs), '\n'.join(haves),
                ', '.join('h%d' % j for j in range(len(groups)))))
    fn = SP + 'Z2CertG_%s.lean' % tag.capitalize()
    open(fn, 'w').write(body)
    print('%-6s  y-degree %2d, %2d coefficient lemmas, %d bytes'
          % (tag, dy, len(groups), len(body)))


for t in (sys.argv[1:] or ['chi', 'gamma', 'beta', 'alpha']):
    emit(t)
