import ZetaLucas.Core
import ZetaLucas.Apery
import ZetaLucas.BrownZudilin
import ZetaLucas.PadicBridge
import ZetaLucas.Letters
import ZetaLucas.TheoremLB
import ZetaLucas.Instances
import ZetaLucas.Kummer
import ZetaLucas.BZFactor12
import ZetaLucas.MinimalForm
import ZetaLucas.BZClosedForm
import ZetaLucas.Defect
