DIR="/home/ubuntu/fable-episode-2/zeta-math-2/work/lb5/";
lf=OpenWrite[DIR<>"eps3.log"];
log[x__]:=(WriteString[lf,x,"\n"];Flush[lf];Print[x]);
log["START ",DateString[]];
Get["/home/ubuntu/riscergosum/RISC/HolonomicFunctions.m"];
log["HF loaded ",DateString[]];
doit[label_,summand_,vars_,tc_]:=Module[{ann,ct1,gb,ct2,t0},
 log["=== ",label,"  vars=",ToString[vars]," ==="];
 t0=AbsoluteTime[];
 ann=TimeConstrained[Annihilator[summand,{S[n],S[k],S[l]}],tc,"TCAP"];
 If[ann==="TCAP"||ann===$Failed,log[label,"  ANN FAILED t=",Round[AbsoluteTime[]-t0],"s"];Return["F"]];
 log[label,"  ann #",Length[ann]," t=",Round[AbsoluteTime[]-t0],"s"];
 Put[ann,DIR<>label<>"_ann.m"];
 t0=AbsoluteTime[];
 ct1=TimeConstrained[CreativeTelescoping[ann,S[k]-1,{S[n],S[l]}],tc,"TCAP"];
 If[ct1==="TCAP"||ct1===$Failed,log[label,"  CT1 FAILED t=",Round[AbsoluteTime[]-t0],"s"];Return["F"]];
 log[label,"  ct1 ntel=",Length[ct1[[1]]]," t=",Round[AbsoluteTime[]-t0],"s"];
 Put[ct1,DIR<>label<>"_ct1.m"];
 t0=AbsoluteTime[];
 gb=TimeConstrained[OreGroebnerBasis[ct1[[1]],OreAlgebra[S[n],S[l]]],tc,"TCAP"];
 If[gb==="TCAP"||gb===$Failed,log[label,"  GB FAILED t=",Round[AbsoluteTime[]-t0],"s"];Return["F"]];
 log[label,"  gb #",Length[gb]," t=",Round[AbsoluteTime[]-t0],"s"];
 Put[gb,DIR<>label<>"_gb.m"];
 t0=AbsoluteTime[];
 ct2=TimeConstrained[CreativeTelescoping[gb,S[l]-1,{S[n]}],tc,"TCAP"];
 If[ct2==="TCAP"||ct2===$Failed,log[label,"  CT2 FAILED t=",Round[AbsoluteTime[]-t0],"s"];Return["F"]];
 log[label,"  ct2 ntel=",Length[ct2[[1]]]," t=",Round[AbsoluteTime[]-t0],"s"];
 Put[ct2,DIR<>label<>"_ct2.m"];
 log[label,"  DONE"];
 ct2];
GK[x_]:=Gamma[n+k+1+x]/(Gamma[n+1]Gamma[k+1+x]);
GL[x_]:=Gamma[n+l+1+x]/(Gamma[n+1]Gamma[l+1+x]);
HK[x_]:=(Gamma[n+1]/(Gamma[k+1+x]Gamma[n-k+1-x]))^2;
HL[x_]:=(Gamma[n+1]/(Gamma[l+1+x]Gamma[n-l+1-x]))^2;
CC[x_]:=Gamma[n+k+l+1+x]/(Gamma[n+1]Gamma[k+l+1+x]);
FF5[ak_,al_,bk_,bl_,g_]:=GK[ak] HK[bk] GL[al] HL[bl] CC[g];
r1=doit["e_g",   FF5[0,0,0,0,ec],  {ec},          900];
r2=doit["e_ak",  FF5[ea,0,0,0,0],  {ea},          900];
r3=doit["e_bk",  FF5[0,0,eb,0,0],  {eb},          900];
r4=doit["e_akal",FF5[ea,ea2,0,0,0],{ea,ea2},     1800];
r5=doit["e_akbk",FF5[ea,0,eb,0,0], {ea,eb},      1800];
r6=doit["e_akg", FF5[ea,0,0,0,ec], {ea,ec},      1800];
r7=doit["e5",    FF5[ea,ea2,eb,eb2,ec],{ea,ea2,eb,eb2,ec},7200];
log["ALL DONE ",DateString[]];
Close[lf];
Exit[];
