DIR="/home/ubuntu/fable-episode-2/zeta-math-2/work/lb5/";
lf=OpenWrite[DIR<>"eps5.log"];
log[x__]:=(WriteString[lf,x,"\n"];Flush[lf];Print[x]);
log["START ",DateString[]];
Get["/home/ubuntu/riscergosum/RISC/HolonomicFunctions.m"];
log["HF loaded ",DateString[]];
GK[x_]:=Gamma[n+k+1+x]/(Gamma[n+1] Gamma[k+1+x]);
GL[x_]:=Gamma[n+l+1+x]/(Gamma[n+1] Gamma[l+1+x]);
HK[x_]:=(Gamma[n+1]/(Gamma[k+1+x] Gamma[n-k+1-x]))^2;
HL[x_]:=(Gamma[n+1]/(Gamma[l+1+x] Gamma[n-l+1-x]))^2;
CC[x_]:=Gamma[n+k+l+1+x]/(Gamma[n+1] Gamma[k+l+1+x]);
FF5[ak_,al_,bk_,bl_,g_]:=GK[ak] HK[bk] GL[al] HL[bl] CC[g];
go[label_,summand_]:=Module[{ann,c1,gg,c2,t0,tot},
  tot=AbsoluteTime[]; log["--- ",label," ---"];
  t0=AbsoluteTime[]; ann=Annihilator[summand,{S[n],S[k],S[l]}];
  log[label," ann #",Length[ann]," t=",Round[AbsoluteTime[]-t0],"s"]; Put[ann,DIR<>label<>"_ann.m"];
  t0=AbsoluteTime[]; c1=CreativeTelescoping[ann,S[k]-1,{S[n],S[l]}];
  log[label," ct1 #",Length[c1[[1]]]," t=",Round[AbsoluteTime[]-t0],"s"]; Put[c1,DIR<>label<>"_ct1.m"];
  t0=AbsoluteTime[]; gg=OreGroebnerBasis[c1[[1]],OreAlgebra[S[n],S[l]]];
  log[label," gb #",Length[gg]," t=",Round[AbsoluteTime[]-t0],"s"]; Put[gg,DIR<>label<>"_gb.m"];
  t0=AbsoluteTime[]; c2=CreativeTelescoping[gg,S[l]-1,{S[n]}];
  log[label," ct2 #",Length[c2[[1]]]," t=",Round[AbsoluteTime[]-t0],"s TOTAL=",Round[AbsoluteTime[]-tot],"s"];
  Put[c2,DIR<>label<>"_ct2.m"];
  ap2=ApplyOreOperator[c2[[1,1]],FF[n]];
  log[label," ORDER=",ToString[Max[Cases[ap2,FF[n+a_.]:>a,Infinity]]]];
  c2];
go["s_g", FF5[0,0,0,0,ec]];
go["s_ak",FF5[ea,0,0,0,0]];
go["s_bk",FF5[0,0,eb,0,0]];
log["ALL DONE ",DateString[]];
Close[lf]; Exit[];
