lf=OpenWrite["/home/ubuntu/fable-episode-2/zeta-math-2/work/lb5/gate4.log"];
log[x__]:=(WriteString[lf,x,"\n"];Flush[lf]);
log["START ",DateString[]];
Get["/home/ubuntu/riscergosum/RISC/HolonomicFunctions.m"];
log["HF loaded"];
DIR="/home/ubuntu/fable-episode-2/zeta-math-2/work/lb5/";
Tsum = Binomial[n+k,n] Binomial[n,k]^2 Binomial[n+l,n] Binomial[n,l]^2 Binomial[n+k+l,n];
Ar[r_,x_]:=HarmonicNumber[n+x,r]-HarmonicNumber[x,r];
Br[r_,x_]:=HarmonicNumber[n-x,r]-HarmonicNumber[x,r];
CC1 := HarmonicNumber[n+k+l,1]-HarmonicNumber[k+l,1];
w3 = HarmonicNumber[n,3] + Ar[3,k] + Ar[3,l] - 1/4 (Ar[2,k] Ar[1,k] + Ar[2,l] Ar[1,l]) - 3/4 (Ar[2,k] Br[1,k] + Ar[2,l] Br[1,l]) - 3/8 (Ar[2,k] + Ar[2,l]) CC1 - 1/8 (Ar[2,k] Ar[1,l] + Ar[2,l] Ar[1,k]);
log["w3 leafcount = ",ToString[LeafCount[w3]]];
summand = Tsum w3;
t0=AbsoluteTime[]; annW = Annihilator[summand,{S[n],S[k],S[l]}];
log["annW #",Length[annW]," in ",Round[AbsoluteTime[]-t0],"s"];
Put[annW, DIR<>"annW.m"];
log["annW support: ",ToString[InputForm[Map[Exponent[#,1]&,{}]]]];
t0=AbsoluteTime[]; ct1 = TimeConstrained[CreativeTelescoping[annW,S[k]-1,{S[n],S[l]},Incomplete->True],9000,"T"];
If[MatchQ[ct1,"T"|$Failed], log["CT-k FAILED ",ToString[ct1]," after ",Round[AbsoluteTime[]-t0],"s"]; Close[lf]; Exit[]];
log["CT-k done in ",Round[AbsoluteTime[]-t0],"s #q=",ToString[Length[ct1[[1]]]]];
Put[ct1, DIR<>"W3_ct1.m"];
t0=AbsoluteTime[]; gb = OreGroebnerBasis[ct1[[1]], OreAlgebra[S[n],S[l]]];
log["GB #",Length[gb]," in ",Round[AbsoluteTime[]-t0],"s"];
t0=AbsoluteTime[]; ct2 = TimeConstrained[CreativeTelescoping[gb,S[l]-1,{S[n]}],9000,"T"];
If[MatchQ[ct2,"T"|$Failed], log["CT-l FAILED ",ToString[ct2]," after ",Round[AbsoluteTime[]-t0],"s"]; Close[lf]; Exit[]];
log["CT-l done in ",Round[AbsoluteTime[]-t0],"s #q=",ToString[Length[ct2[[1]]]]];
Put[ct2, DIR<>"W3_ct2.m"];
ap = ApplyOreOperator[ct2[[1,1]],FF[n]];
ord = Max[Join[{0},Cases[ap, FF[n+aa_.]:>aa, Infinity]]];
log["ORDER = ",ToString[ord]];
log["applied = ",ToString[InputForm[ap]]];
log["DONE ",DateString[]];
Close[lf];Exit[];
